In [2]:
import numpy as np 
from sklearn import datasets

In [24]:
dataset = datasets.load_iris()

data, label = dataset.data, dataset.target

print(type(data), type(label))
print(data[:3], label[:3], np.unique(label))

data = data[label<2]
label = label[label<2]

print(len(data), len(label), np.unique(label))




<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]] [0 0 0] [0 1 2]
100 100 [0 1]


In [94]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle
ERROR: No matching distribution found for pickle


In [103]:
# logistic regression for data, label 
import pickle


class LogisticRegressionClassifier():

    
    def __init__(self, itr=100, lr=0.01, bias=True): 
        self.iter = itr
        self.lr = lr 
        self.bias = bias
        self.loss = []
    
    def save(self, filename):
        with open(filename, 'wb') as f:
            pickle.dump(self, f, protocol=pickle.HIGHEST_PROTOCOL)
    
    def load(model_path):
        with open(model_path, 'rb') as f:
            model = pickle.load(f)
        return model
   
    def cross_entropy(self, y, h, gamma=0.00001):
        return -np.sum(y*np.log(h + gamma) + (1-y)*np.log(1-h + gamma))/ len(self.X)
        
    
    def sigmoid(self, h): 
        
        return 1/(1 + np.exp(-h))
    
    def train(self, X, y): 

        if self.bias:
            X = np.insert(X, 0, 0, axis=1)
        self.X = X
        weights = np.zeros(shape=X.shape[1])
        
        z = np.dot(X, weights)
        h = self.sigmoid(z)
        
        print(X.shape, weights.shape, y.shape, z.shape, h.shape)
        
        for i in range(self.iter):
            z = np.dot(X, weights)
            h = self.sigmoid(z)
            
            derivative = np.dot(X.T ,h-y) 
            weights -= self.lr*derivative
            
            loss = self.cross_entropy(y,h)
            self.loss.append(loss)
#             print(weights)
            if i%10000==0: 
                print(f"loss for iter {i} is : {loss}")

        self.weights = weights
            
    def predict(self, x_test): 
        x_test = np.array(x_test)
        z = np.dot(x_test, self.weights)
        self.class_prob = self.sigmoid(z)
        
        self.labels = np.array([1 if x>0.5 else 0 for x in self.class_prob])
        
        return self.class_prob, self.labels
        
    
    
model = LogisticRegressionClassifier(itr=10000)
model.train(data, label)

print(model.weights)
prob, labels = model.predict([[1,2,3,4,5], [2,3,4,5,6]])
print(model.class_prob, model.labels)

model.save('./test.pkl')

model = LogisticRegressionClassifier.load('./test.pkl')

print(model.weights)
print(model.class_prob, model.labels)

        


(100, 5) (5,) (100,) (100,) (100,)
loss for iter 0 is : 0.6931271807599428
[ 0.         -1.26369942 -4.17581238  6.4249169   2.97745126]
[1. 1.] [1 1]
[ 0.         -1.26369942 -4.17581238  6.4249169   2.97745126]
[1. 1.] [1 1]
