In [3]:
import numpy as np
import torch

#  Softmax and Sigmoid

In [42]:

sigmoid = torch.nn.Sigmoid()
softmax = torch.nn.Softmax()

In [81]:
def msigmoid(inputs):
    sig = 1 / (1 + torch.exp(-1*(inputs)))
    return sig

def msoftmax(inputs):
    sof = torch.exp(inputs) / torch.exp(inputs).sum(1, keepdim=True)
    return sof
    
def npsigmoid(inputs):
    sig = 1 / (1 + np.exp(-1*(inputs)))
    return sig

def maxnpsoftmax(inputs):
#     print(inputs.numpy())
    X = np.exp(inputs.numpy() - np.max(inputs.numpy(), axis=-1, keepdims=True))
    sof = X / X.sum(axis=-1, keepdims=True)
    return sof

def npsoftmax(inputs):
#     print(inputs.numpy())
    X = np.exp(inputs.numpy())
    sof = X / X.sum(axis=-1, keepdims=True)
    return sof

In [82]:
inputs = torch.randint(1,10,(10,2))
# inputs = torch.randn(3)
print(inputs)

# print(sigmoid(inputs))
# print(msigmoid(inputs))
# print(npsigmoid(inputs.numpy()))


print(softmax(torch.tensor(inputs, dtype=torch.float64)))
# print(msoftmax(torch.tensor(inputs, dtype=torch.float64)))
print(npsoftmax(torch.tensor(inputs, dtype=torch.float64)))
print(maxnpsoftmax(torch.tensor(inputs, dtype=torch.float64)))

tensor([[5, 9],
        [4, 2],
        [7, 3],
        [5, 9],
        [1, 2],
        [5, 2],
        [5, 7],
        [3, 4],
        [9, 5],
        [4, 3]])
tensor([[0.0180, 0.9820],
        [0.8808, 0.1192],
        [0.9820, 0.0180],
        [0.0180, 0.9820],
        [0.2689, 0.7311],
        [0.9526, 0.0474],
        [0.1192, 0.8808],
        [0.2689, 0.7311],
        [0.9820, 0.0180],
        [0.7311, 0.2689]], dtype=torch.float64)
[[0.01798621 0.98201379]
 [0.88079708 0.11920292]
 [0.98201379 0.01798621]
 [0.01798621 0.98201379]
 [0.26894142 0.73105858]
 [0.95257413 0.04742587]
 [0.11920292 0.88079708]
 [0.26894142 0.73105858]
 [0.98201379 0.01798621]
 [0.73105858 0.26894142]]
[[0.01798621 0.98201379]
 [0.88079708 0.11920292]
 [0.98201379 0.01798621]
 [0.01798621 0.98201379]
 [0.26894142 0.73105858]
 [0.95257413 0.04742587]
 [0.11920292 0.88079708]
 [0.26894142 0.73105858]
 [0.98201379 0.01798621]
 [0.73105858 0.26894142]]


<ipython-input-82-a49aab270035>:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(softmax(torch.tensor(inputs, dtype=torch.float64)))
<ipython-input-82-a49aab270035>:10: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  print(softmax(torch.tensor(inputs, dtype=torch.float64)))
<ipython-input-82-a49aab270035>:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print(npsoftmax(torch.tensor(inputs, dtype=torch.float64)))
<ipython-input-82-a49aab270035>:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rathe

In [98]:
np.array([[1,2,3], [1,1,1]]).sum(axis=(1))

array([6, 3])